In [2]:
import pandas as pd
import numpy as np

In [6]:
#Joins/merges between two DataFrames

first_df=pd.DataFrame({'ID':[1,2,3,4],
'Name':['Alice','Bob','Charlie','David'],
'Age':[25,30,35,40]})

second_df=pd.DataFrame({'ID':[1,2,3,4],
'Name':['A','B','C','D'],
'Age':[10,20,30,50]})

merged_df=pd.merge(first_df,second_df,on='ID',how='inner',suffixes=('_First','_Second'))
print(merged_df)

   ID Name_First  Age_First Name_Second  Age_Second
0   1      Alice         25           A          10
1   2        Bob         30           B          20
2   3    Charlie         35           C          30
3   4      David         40           D          50

Concat

In [7]:
#Concatination of DataFrames , Ignore index will not consider the previous index values so it becomes as continuous
#if we dont need the index to change use the key to define the source of data
#axis =0 means row wise concatination , axis=1 means column wise concatination
concat_df=pd.concat([first_df,second_df], keys=['First_DF','Second_DF'])
(concat_df)

concat_df.loc['First_DF']

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40

Read data from Url

In [ ]:
#read file from github
url="https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/refs/heads/master/diabetes.csv"

df=pd.read_csv(url)

df

List of Countries by GDP - Load Data from Wikipedia

In [8]:
#Load from HTML
url=r"https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

df_gdp=pd.read_html(url, storage_options={'User-Agent':'Mozilla/5.0'})

df_gdp[2]

,Country/Territory,IMF (2025)[6],World Bank (2024)[7],United Nations (2023)[8]
0,World,117165394,111326370,100834796
1,United States,30615743,28750956,27720700
2,China[n 1],19398577,18743803,17794782
3,Germany,5013574,4685593,4525704
4,Japan,4279828,4027598,4204495
...,...,...,...,...
217,Kiribati,321,308,289
218,Marshall Islands,302,290,270
219,Nauru,172,163,176
220,Montserrat,—N/a,—N/a,80
221,Tuvalu,58,62 (2023),68